### PR TITLE
Docker alpine + Node Upgrade

### PR DESCRIPTION
**Pull request by captn3m0**
- Tested both with and without Docker on Node 9.11.1

Takes down the image size from 690MB to 115MB

### CODE REVIEW

**Comment by captn3m0** [comment]
Built on [Docker Cloud](https://cloud.docker.com/swarm/captn3m0/repository/registry-1.docker.io/captn3m0/speedtest-exporter/builds/e3e3e3c9-b231-476b-8442-d591b2cdb27e) as `captn3m0/speedtest-exporter:alpine`

**Comment by captn3m0** [comment]
@stefanwalther can this be merged?

**Comment by stefanwalther** [comment]
Sorry, didn't see, will give it a try and then come back to you/merge.
Thx a lot for the contribution!

**Comment by captn3m0** [comment]
@stefanwalther reminder to take a look.

**Comment by stefanwalther** [comment]
Done, thx a lot!

**Comment by stefanwalther** [comment]
Seems that there is an issue ... I have a few improvements available to this repo (v2.0), which I'll try to merge ASAP.

**Pull request merged**
